spring:
  datasource:
    url: jdbc:postgresql:localhost:5432/project_management
    username: root
    password: root
  jpa:
    database: postgresql
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

#Mail properties

