spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/project_management
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false

jwt:
  header: X-Auth-Token
  secret: da7ca69f41dce5179752a7546dfa0959
  expiration: 259200 #3days
role:
  header: X-Role-Header