export const API_CALL = 'API_CALL';

export const MAKE_AUTH_REQUEST = 'MAKE_AUTH_REQUEST';
export const MAKE_AUTH_FAILED = 'MAKE_AUTH_FAILED';
export const MAKE_AUTH_SUCCESS = 'MAKE_AUTH_SUCCESS';

export const FETCH_USER_DATA_REQUEST = 'FETCH_USER_DATA_REQUEST';
export const FETCH_USER_DATA_SUCCESS = 'FETCH_USER_DATA_SUCCESS';
export const FETCH_USER_DATA_FAILED = 'FETCH_USER_DATA_FAILED';

export const LOGOUT_USER = 'LOGOUT_USER';

export const UPDATE_TOKEN_REQUEST = 'UPDATE_TOKEN_REQUEST';
export const UPDATE_TOKEN_SUCCESS = 'UPDATE_TOKEN_SUCCESS';
export const UPDATE_TOKEN_FAILED = 'UPDATE_TOKEN_FAILED';

export const FETCH_PROJECT_DATA_REQUEST = 'FETCH_PROJECT_DATA_REQUEST';
export const FETCH_PROJECT_DATA_SUCCESS = 'FETCH_PROJECT_DATA_SUCCESS';
export const FETCH_PROJECT_DATA_ERROR = 'FETCH_PROJECT_DATA_ERROR';
